package com.example.nore.turndown.entity.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usuarioDaoConfig;
    private final DaoConfig reporteDaoConfig;
    private final DaoConfig jobDaoConfig;
    private final DaoConfig imageInfoDaoConfig;
    private final DaoConfig taskJobDaoConfig;

    private final UsuarioDao usuarioDao;
    private final ReporteDao reporteDao;
    private final JobDao jobDao;
    private final ImageInfoDao imageInfoDao;
    private final TaskJobDao taskJobDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usuarioDaoConfig = daoConfigMap.get(UsuarioDao.class).clone();
        usuarioDaoConfig.initIdentityScope(type);

        reporteDaoConfig = daoConfigMap.get(ReporteDao.class).clone();
        reporteDaoConfig.initIdentityScope(type);

        jobDaoConfig = daoConfigMap.get(JobDao.class).clone();
        jobDaoConfig.initIdentityScope(type);

        imageInfoDaoConfig = daoConfigMap.get(ImageInfoDao.class).clone();
        imageInfoDaoConfig.initIdentityScope(type);

        taskJobDaoConfig = daoConfigMap.get(TaskJobDao.class).clone();
        taskJobDaoConfig.initIdentityScope(type);

        usuarioDao = new UsuarioDao(usuarioDaoConfig, this);
        reporteDao = new ReporteDao(reporteDaoConfig, this);
        jobDao = new JobDao(jobDaoConfig, this);
        imageInfoDao = new ImageInfoDao(imageInfoDaoConfig, this);
        taskJobDao = new TaskJobDao(taskJobDaoConfig, this);

        registerDao(Usuario.class, usuarioDao);
        registerDao(Reporte.class, reporteDao);
        registerDao(Job.class, jobDao);
        registerDao(ImageInfo.class, imageInfoDao);
        registerDao(TaskJob.class, taskJobDao);
    }
    
    public void clear() {
        usuarioDaoConfig.getIdentityScope().clear();
        reporteDaoConfig.getIdentityScope().clear();
        jobDaoConfig.getIdentityScope().clear();
        imageInfoDaoConfig.getIdentityScope().clear();
        taskJobDaoConfig.getIdentityScope().clear();
    }

    public UsuarioDao getUsuarioDao() {
        return usuarioDao;
    }

    public ReporteDao getReporteDao() {
        return reporteDao;
    }

    public JobDao getJobDao() {
        return jobDao;
    }

    public ImageInfoDao getImageInfoDao() {
        return imageInfoDao;
    }

    public TaskJobDao getTaskJobDao() {
        return taskJobDao;
    }

}
