package com.example.nore.turndown.entity.dao;;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.nore.turndown.entity.dao.Usuario;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table USUARIO.
*/
public class UsuarioDao extends AbstractDao<Usuario, Long> {

    public static final String TABLENAME = "USUARIO";

    /**
     * Properties of entity Usuario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property Apellido = new Property(2, String.class, "apellido", false, "APELLIDO");
        public final static Property Usuario = new Property(3, String.class, "usuario", false, "USUARIO");
        public final static Property Contraseña = new Property(4, String.class, "contraseña", false, "CONTRASEÑA");
        public final static Property ActiveUser = new Property(5, Boolean.class, "activeUser", false, "ACTIVE_USER");
    };

    private DaoSession daoSession;


    public UsuarioDao(DaoConfig config) {
        super(config);
    }
    
    public UsuarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'USUARIO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'NOMBRE' TEXT NOT NULL ," + // 1: nombre
                "'APELLIDO' TEXT NOT NULL ," + // 2: apellido
                "'USUARIO' TEXT NOT NULL ," + // 3: usuario
                "'CONTRASEÑA' TEXT NOT NULL ," + // 4: contraseña
                "'ACTIVE_USER' INTEGER);"); // 5: activeUser
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USUARIO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Usuario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
        stmt.bindString(3, entity.getApellido());
        stmt.bindString(4, entity.getUsuario());
        stmt.bindString(5, entity.getContraseña());
 
        Boolean activeUser = entity.getActiveUser();
        if (activeUser != null) {
            stmt.bindLong(6, activeUser ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(Usuario entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Usuario readEntity(Cursor cursor, int offset) {
        Usuario entity = new Usuario( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nombre
            cursor.getString(offset + 2), // apellido
            cursor.getString(offset + 3), // usuario
            cursor.getString(offset + 4), // contraseña
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // activeUser
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Usuario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.getString(offset + 1));
        entity.setApellido(cursor.getString(offset + 2));
        entity.setUsuario(cursor.getString(offset + 3));
        entity.setContraseña(cursor.getString(offset + 4));
        entity.setActiveUser(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Usuario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Usuario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
